# Generated by Django 3.0.5 on 2020-10-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201003_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-id']},
        ),
    ]
